CREATE TABLE images (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  user_id INT(11) UNSIGNED NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE friendspivot (
  user_from INT(11) UNSIGNED,
  user_to INT(11) UNSIGNED
);

CREATE TABLE requestpivot (
  user_from INT(11) UNSIGNED,
  user_to INT(11) UNSIGNED
);